### ISSUE TITLE
'gpt-3.5-turbo' engine returns 404

### ISSUE THREAD

**Issue by ogourment** [nagstler/chatgpt-ruby#2]
Using 'text-davinci-003' works but any engine after that leads to a `exception_with_response': 404 Not Found 
Code:
```
  params = {
    engine: 'gpt-3.5-turbo' ##  text-davinci-003 works fine
  }
  completions = client.completions(prompt, params)
```

I was successful with cURL:

```
curl https://api.openai.com/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-d '{
   "model": "gpt-3.5-turbo",
    "messages": [
        {
            "content": "Hello, how are you?",
            "role": "user"
        }
    ]
}'
```

**Comment by ogourment** [comment]
Got it, it should be an improvement request for it to use v1/chat/completions instead of /completions. I should have looked at the code earlier but I guess I assumed the "chatgpt" in "chatgpt-ruby" meant it uses the newer chat models. My bad

**Comment by nagstler** [comment]
> Using 'text-davinci-003' works but any engine after that leads to a `exception_with_response': 404 Not Found Code:
> 
> ```
>   params = {
>     engine: 'gpt-3.5-turbo' ##  text-davinci-003 works fine
>   }
>   completions = client.completions(prompt, params)
> ```
> 
> I was successful with cURL:
> 
> ```
> curl https://api.openai.com/v1/chat/completions \
> -H "Content-Type: application/json" \
> -H "Authorization: Bearer $OPENAI_API_KEY" \
> -d '{
>    "model": "gpt-3.5-turbo",
>     "messages": [
>         {
>             "content": "Hello, how are you?",
>             "role": "user"
>         }
>     ]
> }'
> ```

In terms of models, the completions endpoint is designed to work with base GPT-3 models like text-davinci-001, text-davinci-002, and so on. The chat endpoint is designed to work with chat models, such as gpt-3.5-turbo.

**Comment by nagstler** [comment]
@ogourment I've implemented the changes to add support for the newer models like 'gpt-3.5-turbo'.

Here is an example of how to use the new `chat` method:

```ruby
messages = [
  { 'role' => 'system', 'content' => 'You are a helpful assistant.' },
  { 'role' => 'user', 'content' => 'Who won the world series in 2020?' }
]
response = client.chat(messages)
puts response['choices'].map { |c| c['message']['content'] }
```
The README has also been updated to include instructions and examples for this new feature.

These changes are included in the latest release, v2.0.0. Make sure you update your Gem version to 2.0.0

Please give it a try and let me know if you encounter any issues.

**Comment by nagstler** [comment]
Closing this issue as the feature has been implemented.

**Comment by ogourment** [comment]
just confirming it works like a charm. thanks
